cscareerhub/megabot

- .github/pull_request_template.md
- README.md
Update contributing section of docs to be clearer, add a PR naming convention, and update checklist items in the pull request template and change checklist to actual checkmarks.
[x] Branch is named correctly
[x] Updated relevant documentation
[ ] Tested with a tester bot
N/A
> [docs] Update docs, add PR naming convention, and update pull request template

- .gitignore
- babel.config.js
- lerna.json
- package.json
- yarn.lock
Update dependencies and configs, restructure packages, update scripts
[x] Branch is named correctly
[x] Updated relevant documentation
[ ] Tested with a tester bot
1. Run `yarn build`
2. Each package should output a `lib` folder based on `src`
3. Running `yarn start` and `yarn serve` won't work yet, but the build part should
4. `yarn test` and `yarn coverage` should try to execute jest on each package, but won't work because there are no tests yet.
> [misc] Update dependencies and configs, restructure packages, update scripts

- README.md
Update .env setup instructions
N/A
> [docs] Update .env setup

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> [misc] Bug report and feature request issue templates

- .eslintrc.js
- jest.config.js
- package.json
- src/index.js
- src/utils/constants.js
- src/utils/index.js
- src/utils/perms/tests/index.test.js
- src/utils/settings/tests/index.test.js
- src/utils/tests/index.test.js
- yarn.lock
Implement basic message parser that can be built on, add valid commands and prefix constants, and add/update jest configs and lint rules
1. Run `yarn lint`
2. All tests should pass
3. Run tester bot
4. Add console logs in `parseMessage` to test
> [feature] Implement message parser and jest configs

- .github/workflows/ubuntu-test.yml
Creates github workflow to use for future PRs to automate linting and testing.
Observe the auto runs here: https://github.com/cscareerhub/megabot/actions
> [feature] Automate linting and unit testing

- specs/pins.spec.md
The title of the pins spec was "Compensation", should be "Pins" 
N/A
> [docs] Fix title of pins spec

- .env.template
- README.md
- src/client.js
- src/constants.js
Add docs corresponding to .env and env nums
N/A
> [misc] Add docs corresponding to .env and env nums

- .github/pull_request_template.md
Keyword will automatically close related issues.
N/A
> [misc] Add resolves keyword to pull request template

- package.json
- src/bots/ping/index.js
- src/bots/pins/handler.js
- src/client.js
- src/constants.js
- src/utils/dispatcher.js
- src/utils/tests/dispatcher.test.js
- yarn.lock
Improved accessibility of Message object, attach more constants to client to clean up
Ping bot should still work
> [feat] Improved accessibility of Message object, attach more constants to client

- .github/workflows/ubuntu-test.yml
Workflow causing errors when starting up because of integrity issues
Run workflow
> [bug] yarn cache issues in workflow

- .github/workflows/ubuntu-test.yml
- README.md
- package.json
**Related Issue**: resolves #
We have a `yarn lint` script and a `yarn test` script, so I added a `yarn format` as well. 
Run `yarn format`
> [misc] Add formatting script/shortcut and format project

- src/bots/comp/constants.js
- src/bots/comp/embed.js
- src/bots/comp/handler.js
- src/bots/comp/index.js
- src/bots/pins/index.js
Cleans up the basic salary bot starting code
Test with `++salary` in the server... I would write unit tests but I'm going to change around more things in a follow-up PR.
> [misc] First pass clean up of basic salary bot code

- .github/workflows/codeql-analysis.yml
CodeQL is a tool for automated vulnerability testing which is potentially a nice-to-have.
This is auto generated by github, not manually created.
N/A
> [feature] Add code quality analysis to workflow

- package.json
- src/bots/ama/tests/addEvent.test.js
- src/bots/ama/tests/listEvents.test.js
**Related Issue**: resolves #58
Adds in-memory database that should also take care of race conditions.
N/A
> [feature] add in-memory database for testing

- src/bots/ama/constants.js
- src/bots/ama/index.js
- src/bots/ama/subCommands/info.js
- src/bots/ama/subCommands/tests/info.test.js
**Related Issue**: resolves #79
Adds private message information for upcoming event
`++ama info` and see private message of either upcoming event or err.
> [feature] Add info subcommand to AMA

- src/bots/ama/constants.js
- src/bots/ama/subCommands/addEvent.js
- src/bots/ama/subCommands/deleteEvent.js
- src/bots/ama/subCommands/editEvent.js
- src/bots/ama/subCommands/tests/addEvent.test.js
- src/bots/ama/subCommands/tests/deleteEvent.test.js
- src/bots/ama/subCommands/tests/editEvent.test.js
**Related Issue**: resolves #56
Limits delete, edit and add to mods+
Try `++ama add` `++ama edit` `++ama delete` with and without mod perms.
> [feature] Add mod check to AMA commands

- package.json
- yarn.lock
Attempts to solve vulnerability issue created by dependabot
N/A
> [misc] bump version of mongoose for mquery

- README.md
**Related Issue**: resolves #57 
Check out the README
> [feature] Add badges to README

- src/bots/pins/index.js
- src/client.js
- src/constants.js
- src/utils/index.js
- src/utils/perms.js
When limiting dev bot things to dev channel, forgot about the reaction listeners
Additionally added the shouldListen util and alphabetized util functions
Pinning works but only in dev channel when in development
> [bug] Limit pinning to dev channel on dev bot, create shouldListen util

- src/bots/ama/constants.js
- src/bots/ama/subCommands/deleteEvent.js
- src/bots/ama/subCommands/tests/deleteEvent.test.js
- src/bots/pins/constants.js
- src/bots/pins/subCommands/pinByReaction.js
- src/bots/pins/subCommands/tests/pinByReaction.test.js
- src/bots/settings/constants.js
- src/bots/settings/subCommands/setDevChannel.js
- src/bots/settings/subCommands/setModChannel.js
- src/bots/settings/subCommands/tests/setDevChannel.test.js
- src/bots/settings/subCommands/tests/setModChannel.test.js
- src/bots/settings/subCommands/tests/updateEnvVar.test.js
- src/bots/settings/subCommands/updateEnvVar.js
Update areas without strings constant
Messages and bot responses should still work
> [misc] Update areas without strings constant

- src/bots/ama/subCommands/tests/listEvents.test.js
- src/bots/modchat/tests/messageHandler.test.js
- src/utils/index.js
- src/utils/tests/index.test.js
Adds and updates unit tests
N/A
> [misc] Add and update unit tests

- src/utils/perms.js
- src/utils/tests/perms.test.js
**Related Issue**: resolves #106 
1. Have someone with "Server Contributor" or anything that is more than "Contributor" try pin
> [bug] Detect all contributor roles and fix role finding

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- .github/workflows/stale-pull-requests.yml
- src/bots/ama/subCommands/deleteEvent.js
- src/bots/ama/subCommands/editEvent.js
- src/utils/index.js
**Related Issue**: #111
Will tick off boxes once they are in dev branch
Doesn't need tests
> [feature] catch actual errors and add stale PR closer

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- .github/workflows/stale-pull-requests.yml
- package.json
- src/bots/ama/subCommands/deleteEvent.js
- src/bots/ama/subCommands/editEvent.js
- src/client.js
- src/utils/index.js
- src/utils/rawMessageProxy.js
- src/utils/tests/rawMessageProxy.test.js
- yarn.lock
**Related Issue**: resolves #114
1. Disable bot
2. Type message (so msg not in cache of bot)
3. Enable bot
4. Try pin using emote 📌
> [feature] Add raw reactions to bot

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- README.md
**Related Issue**: #111 (david-dm.org) and #116
Not entirely resolved but looking as a hotfix
Try to deploy
> [feature] change workflow for checkout and readme

- .github/workflows/deploy-development.yml
This is for testing more. Cannot replicate locally
> [POC] Add debug command to dev deploy script

- .github/workflows/deploy-development.yml
> [POC] Deployment Script

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
**Related Issue**: resolves #116
Fixes script by exposing NVM to docker
N/A
> [bug] Fix deployment scripts by adding export to NVM

- package.json
- src/client.js
- yarn.lock
Updates packages to newest stable
N/A
> [feature] Update dependencies

- package.json
- src/bots/ping/index.js
Ping now shows latest bot version
- Do ++ping and should see version
> [feature] Make ping command show bot version

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- package.json
- src/bots/modchat/messageHandler.js
- src/utils/index.js
**Related Issue**: resolves #116 and #102
- Add fetch to update versioning
- Make modchat delete any message sent in non-DM channels (bug had it at 2 args minimum)
N/A
> [bug] Various fixes

- package.json
- src/bots/modchat/constants.js
- src/bots/modchat/index.js
- src/bots/modchat/reactionHandler.js
- src/bots/modchat/tests/reactionHandler.test.js
**Related Issue**: resolves #122
Write purpose here
- react with ⚠️ to a message as a contributor
- this will warn in moderator channel (should see message with embed)
> [feature] Alert Bot

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- README.md
- package.json
- src/bots/modchat/constants.js
- src/bots/modchat/index.js
- src/bots/modchat/messageHandler.js
- src/bots/modchat/reactionHandler.js
- src/bots/modchat/tests/reactionHandler.test.js
- src/bots/ping/index.js
- src/client.js
- src/utils/index.js
- yarn.lock
changelog:
- Add alert system for contributors
- Fixes for deployment
- ping shows bot version
- update dependencies
> [deploy] development -> master

- package.json
- specs/misc.spec.md
- src/bots/misc/constants.js
- src/bots/misc/index.js
- src/bots/misc/subCommands/privateMessage.js
- src/bots/misc/subCommands/tests/privateMessage.test.js
- src/bots/modchat/reactionHandler.js
- src/constants.js
- src/index.js
**Related Issue**: resolves #143 resolves #142
Creates ability for mods+ to private message users
++misc pm @user message
> [feature] Add Private Messaging Bot

- src/bots/misc/index.js
- src/bots/misc/subCommands/lmgtfy.js
- src/bots/misc/subCommands/tests/lmgtfy.test.js
**Related Issue**: resolves #N/A
temporarily address questions that should be googled
Run command in a channel
> add secret command

- .github/workflows/deploy-development.yml
- package.json
- src/bots/misc/subCommands/lmgtfy.js
- src/bots/misc/subCommands/tests/lmgtfy.test.js
**Related Issue**: resolves #N/A
Change link because lmgtfy.app is not as funny
Run command
> [feature] Change lmgtfy link
